services: 

#Konfiguracja Cowrie (SSH/TELNET)
  cowrie: 
   image: cowrie/cowrie:latest 
   container_name: COWRIE  
   restart: always 
   ports: 
    - "2222:2222" 
    - "2223:2223" 
   networks:
    honeynet:
     ipv4_address: 172.25.0.10 
   volumes: 
      - ./cowrie_logs:/cowrie/cowrie-git/var/log/cowrie
      - ./cowrie_downloads:/cowrie/cowrie-git/var/lib/cowrie/downloads
   deploy:
    resources:
     limits:
      cpus: '0.50'
      memory: 512M
   logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
#Konfiguracja Dionaea
  dionaea:
   image: dinotools/dionaea:latest
   container_name: DIONAEA
   restart: always
   ports:
    - "21:21"
    - "42:42" 
    - "135:135" 
    - "8445:445" 
    - "14333:1433"
    - "3306:3306"
    - "5060:5060"
    - "5061:5061"
   networks: 
    honeynet:
     ipv4_address: 172.25.0.11
   volumes: 
   - ./dionaea_data:/opt/dionaea/var/lib/dionaea 
   - ./dionaea_logs:/opt/dionaea/var/log/dionaea  
   deploy:
    resources:
     limits:
      cpus: '0.50'
      memory: 512M
   logging:
    driver: "json-file"
    options:
     max-size: "100m"
     max-file: "3"
#Konfiguracja Real-Os
  real-os:
   build: ./real-os 
   container_name: REAL-OS 
   restart: always
   privileged: true 
   ports:
    - "2224:22" 
   networks:
    honeynet:
     ipv4_address: 172.25.0.12
   volumes:
    - ./real-os/logs:/var/log  
   deploy:
    resources:
     limits: 
      cpus: "2.0"
      memory: "2G"
   healthcheck:
    test: ["CMD", "service", "ssh", "status"]
    interval: 45s
    timeout: 10s
    retries: 3
   logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
#Konfiguracja Snort NIDS
  snort:
    image: linton/docker-snort:latest
    container_name: snort
    restart: always
    network_mode: "host"
    cap_add:
     - NET_ADMIN #capability
    volumes:
      - ./snort_logs:/var/log/snort
      - ./snort_rules/local.rules:/etc/snort/rules/local.rules

    command: snort -A fast -q -c /etc/snort/etc/snort.conf -i bridge-honeypot -k none
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

#Portainer 
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - honeynet

#Promtail 
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./config/promtail-config.yaml:/etc/promtail/config.yaml:ro
      - ./cowrie_logs:/var/log/cowrie:ro
      - ./dionaea_logs:/var/log/dionaea:ro
      - ./snort_logs:/var/log/snort:ro
      - ./real-os/logs:/var/log/real-os:ro
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - honeynet
    depends_on:
      - loki

#Loki 
  loki:
    image: grafana/loki:latest
    user: "0"
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - honeynet

#Grafana 
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Hasło startowe (zmienisz je po zalogowaniu)
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - honeynet
    depends_on:
      - loki
        
#Wirtualny switch
networks:
 honeynet:
  driver: bridge #virtual switch
  driver_opts:
    com.docker.network.bridge.name: bridge-honeypot #NAZWA KARTY SIECIOWEJ dla snorta
  ipam: #IP Address Management (use standard addresation)
   driver: default
   config:
    - subnet: 172.25.0.0/24 #range from 172.25.0.1 - 172.25.0.254

volumes:
  portainer_data:
  grafana_data:
